### ISSUE TITLE
"My" position command from Home Assistant

### ISSUE THREAD

**Issue by ocadik** [Nickduino/Pi-Somfy#105]
Im using Home Assistant to control covers with Pi-Somfy.

Is possible to use "my" command from Home Assistant(via MQTT), just like from the webe server runnig on Pi-Somfy ?

Now I can only use service covers.open/close. .

**Comment by rbswift** [comment]
Yes with MQTT...

`mosquitto_pub -t "somfy/0x279623/level/cmd" -m "STOP"`

I don't use HA so no idea how to configure that sorry.

**Comment by ocadik** [comment]
> Yes with MQTT...
> 
> `mosquitto_pub -t "somfy/0x279623/level/cmd" -m "STOP"`
> 
> I don't use HA so no idea how to configure that sorry.

It helped a lot, just add a payload STOP and its working now
