### ISSUE TITLE
[Question / Feature Request] Home Assistant addon + ESP32/8622 nodes?

### ISSUE THREAD

**Issue by jaddel** [Nickduino/Pi-Somfy#108]
Hi Everyone, 

the basic idea is to run the [Home Assitant Addon ](https://github.com/Nickduino/Pi-Somfy/issues/87) provided by "Nickduino" and use ESP32/8622 nodes for the RF communication.

Would this be easily possible?

**Comment by jaddel** [comment]
just found this, I guess it does the job :) 

https://github.com/Nickduino/Somfy_Remote

**Comment by geokscott** [comment]
Share your code when you get it working.....

**Comment by geokscott** [comment]
This guy did a nice job:
https://github.com/RoyOltmans/somfy_esp8266_remote_arduino
