### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ukrolelo** [Nickduino/Pi-Somfy#121]
Greetings, i dont see discussion tab to ask a question.
I have read that when using other options than hub or remote,my remotes can go out of sync as the codes changes every some time? Is it true? I would need to stop using remotes?
Thank you

**Comment by Nickduino** [comment]
The remotes use rolling codes to increase security.

This won't be an issue because your virtual remotes will use another address than your physical remotes: you can use both without risking to lose your sync
