### ISSUE TITLE
Somfy Smoove io

### ISSUE THREAD

**Issue by zorbas78** [Nickduino/Pi-Somfy#126]
Hi, just a newbie question - or maybe i get this alle wrong

I have a somfy shutter (smoove io) which is a scrambled network as far as i know. Does this script solve the scrambling also? How does it connect to my shutters? 

thanks

**Comment by Nickduino** [comment]
If it's using the io homecontrol protocol, the script cannot do anything.

If it's the RTS protocol, it "solves the scrambling", yep
