### ISSUE TITLE
FS1000A transmitter versions

### ISSUE THREAD

**Issue by wewa00** [Nickduino/Pi-Somfy#135]
Hello,

there seem to be different versions of the FS1000A transmitter available and the distributors do not differentiate between the different versions. But in the following pictures you can see two different versions (never mind the antenna soldered to the wrong location).

![image](https://user-images.githubusercontent.com/5518631/148994276-8a2bcc1c-8b1c-463b-8689-08c7e27f60a8.png)
![image](https://user-images.githubusercontent.com/5518631/148994350-f97259d0-22db-48ce-86d4-173f5e2a8c3b.png)

Also you seemed to use two different versions in your description. The version I placed left in my pictures seems to equal https://github.com/Nickduino/Pi-Somfy/blob/master/documentation/RF%20Transmitter%20back.jpg and the version I placed right seems to equal https://github.com/Nickduino/Pi-Somfy/blob/master/documentation/RF%20Transmitter%20front.jpg.

So which is the correct version to be used? Or do the differences not matter?

Best regards
wewa

**Comment by Nickduino** [comment]
It shouldn't matter, people have used all kind of transmitters.
Just make sure you emit on 433.**42** (and that the antenna is soldered to the right pad...)
