### ISSUE TITLE
DIfference between old and new blinds

### ISSUE THREAD

**Issue by PederHatlen** [Nickduino/Pi-Somfy#148]
I have a set of old blinds from ~2009, and some new ones from 2018.
The old ones work great with the system, but the new ones doesn't.
After lending a HackRF for testing I found out that the new ones operate at about 434.48 mhz instead of the normal ~433.4 mhz. It also looks like they use some other type of protocol (not much experience in the field of radio, but it looks different).
I haven't seen any other issues about this but I'll include some pictures of the controllers and readings.

The readings from the HackRF:
![SomfyNewVSOld](https://user-images.githubusercontent.com/90681596/192093033-d65799b2-771e-4c8b-8ef7-2d0f1888cc8a.png)

The new controllers:
![NewSomfyRemotes](https://user-images.githubusercontent.com/90681596/192092697-ba8c89af-96db-4ce0-b940-cf562614c016.jpg)

Old controller:
![OldSomfyRemote](https://user-images.githubusercontent.com/90681596/192092701-f050b992-279d-4dec-a387-15690b2eefeb.jpg)

**Comment by Nickduino** [comment]
Your new blinds use a different protocol: Io homecontrol

It's objectively a much better one...but Pi-Somfy can't talk with them.
