### ISSUE TITLE
Raspberry Pi Pico W Compatibility

### ISSUE THREAD

**Issue by vapouryh** [Nickduino/Pi-Somfy#157]
Hi there,

I'm super excited to try and get this project working as I do not want to spend over £200 on a TaHoma switch lol.
I'm wondering if this project would be able to run on a Raspberry Pi Pico W running MicroPython using the same transmitter and GPIO pins?
For me using the Pico W is just smaller and a more cost effective option than having to buy a full Raspberry Pi board.

**Comment by Nickduino** [comment]
I don't see a reason for it not to work as long as python works properly
