### ISSUE TITLE
About changing the saw oscillator

### ISSUE THREAD

**Issue by GatienC** [Nickduino/Pi-Somfy#16]
Hi !

I'm pulling another issue because I don't know how to change the saw oscillator and i cant' find anything on google. Do i have to desolder the actual oscillator and solder the new one or is there something else I don't get ? :)

Anyway thanks for everything !

**Comment by lfliess** [comment]
You got it right, got to desolder the old one first

**Comment by Nickduino** [comment]
Yes, it's that "simple"

Be prepared to spend a good amount of time on the desoldering job if you're not used to it

**Comment by GatienC** [comment]
Thanks ! Any advices about desoldering ? :)

**Comment by Nickduino** [comment]
Heat one pad and try prying gently on the oscillator (with a toothpick, for instance). If it moves slightly, repeat with the second leg, then the third, then go back to the first...
Once you can cut its leads, do that and remove the remaining leads.

Or put a big blob of solder and heat all three pads and legs at once.

Or use the classic method, one pad at a time with desoldering braid.


Or whatever suits you, really

**Comment by GatienC** [comment]
Thanks ! :) I'll try it next weekend

**Comment by kjellhult** [comment]
When you re-solder the new emitter to the board, keep in mind that one pin is grounded to the metal case and the others have *very tiny* insulators around their pins.  Be sure to clean up your excess solder very well, and maybe put a tiny spacer between the case and the board to prevent any shorting to the other pins.
