### ISSUE TITLE
433,42 MHz Resonator not available for Europe?

### ISSUE THREAD

**Issue by s4thoste** [Nickduino/Pi-Somfy#168]
I am looking for a Oscillator with 433,42Mhz which is shipped to Germany/Europe but I cannot find a single one.
Does anyone know how to get it?

**Comment by Nickduino** [comment]
I'm surprised you couldn't find one on eBay/AliExpress

**Comment by Nickduino** [comment]
![image](https://github.com/user-attachments/assets/d10fe6f4-1421-4d77-a65f-1582cc344835)

https://www.aliexpress.com/item/1005005625251557.html

**Comment by s4thoste** [comment]
Unfortunately, this one can also not shipped to Germany

**Comment by Nickduino** [comment]
Try contacting the store?

![image](https://github.com/user-attachments/assets/6b51a74f-c24b-4d41-8e12-8d7a77005213)
https://tpake.aliexpress.com/store/912479009?spm=a2g0o.detail.0.0.60afPudCPudCb4

**Comment by tfcarlin** [comment]
I have a bunch of components from my exploration of Somfy radios. I'm happy to ship these all to you if interested.
![IMG_0655](https://github.com/user-attachments/assets/74e75c0e-cbcd-4705-9ac9-91ccb91a42d5)

**Comment by s4thoste** [comment]
This would be fantastic for me! 
Just Tell what I have to do for it

**Comment by tfcarlin** [comment]
Let me know how to get in touch with you and we'll coordinate there.

**Comment by s4thoste** [comment]
> Let me know how to get in touch with you and we'll coordinate there.

Perfect, you can send me an E-Mail and I'll provide you with my details :-)

s4thoste@gmx-topmail.de

**Comment by Nickduino** [comment]
> I'm happy to ship these all to you if interested.

What a nice gesture!!!

Do you have 433.42 MHz crystals, though?

**Comment by tfcarlin** [comment]
The only crystals are the ones soldered to the boards.

**Comment by Nickduino** [comment]
But the original ones at 433.92, right?
So that won't solve @s4thoste's issue.

But I see you have plenty of CC1101, which might work with Pi-Somfy (not sure, you'd have to learn how to work with these) and will absolutely work with an ESP and https://github.com/rstrouse/ESPSomfy-RTS

**Comment by tfcarlin** [comment]
If you zoom in you'll see they are 433.4. I replaced the originals...sort of foggy on the details so many years later. I then switched to CC1101 solutions which worked well on a RaspPi as well. I think there will be something in the batch that should work...and not a bad deal for the price of shipping.

**Comment by Nickduino** [comment]
> If you zoom in you'll see they are 433.4.

All the better.


> not a bad deal for the price of shipping.

No, it's very generous of you



You should check out ESPSomfy-RTS. Especially since you use Home Assistant.
