### ISSUE TITLE
additions to great project

### ISSUE THREAD

**Issue by MichaelB2018** [Nickduino/Pi-Somfy#17]
Finally got my pi-somfy to run (issue #13 took me a while to resolve.) So I upgraded the script to Python 3, added a command line interface to it so that it can easily operate via cron, then added a flask based web-site to it that allows to program & configure multiple shutters to operate at a reasonable complex schedule (instead of hard coding the schedule) and finally built an Amazon Alexa interface, so shutters react to voice commands. Some screen shots are attached for your reference. 

So the question is if you want to take my code and check it in in the main repository (preferred, I can send it over if you want). Alternatively if you prefer I could fork the project too.

---------------------
![p1](https://user-images.githubusercontent.com/38872689/51578572-fe76d980-1e8b-11e9-95b7-79e4b5c311a8.png)
---------------------
![p2](https://user-images.githubusercontent.com/38872689/51578574-fe76d980-1e8b-11e9-9996-8451641ad806.png)
---------------------
![p3](https://user-images.githubusercontent.com/38872689/51578575-fe76d980-1e8b-11e9-875d-4e7c816da8f7.png)
---------------------
![p4](https://user-images.githubusercontent.com/38872689/51578577-fe76d980-1e8b-11e9-90e5-74c3c02d1ed3.png)

**Comment by Nickduino** [comment]
That sounds absolutely brilliant!
(I've been wanting to add Alexa support for a few weeks, now)


Sorry for the issue #13, I thought it was solved.


Upgraded to python 3: is it still backward compatible with python 2.7 (which is still used by a lot of persons, so that matters)?

Code update: I believe the git way of doing things would be for you to fork the project and do a pull request, and then for me to accept it in the main repository (that way, people know it's your contribution). But if it's too cumbersome you, I can also update the project directly.

**Comment by Nickduino** [comment]
Two ideas about the GUI:

- add a "Program" button either in the "Add/Remove" section (preferred) or in the "Manual Operation" section
- add seconds in the "Scheduled Operation" section and an option to send a stop signal: in the morning, I only partially open the blinds in my bedroom (i.e. just enough to see sunlight) **OR** keep the HH:MM but just add a tickable box saying "Stop after [XX] seconds" (preferred)

**Comment by MichaelB2018** [comment]
ok, will fork it and check it in
- The "Program" button will come up automatically when you "Add" a shutter
- the seconds delay is a feature that is already coded at the back-end, but not yet exposed on the GUI. Will add it there before checking in. 
Give me a few days to complete this.

**Comment by alxlaxv** [comment]
Well done @MichaelB2018 
I will follow that closely!

**Comment by waltner** [comment]
Looks great!

As this is a major upgrade of the repo, would it also make sense to translate the variables in the code to English? I do speak some French so it was not an issue for me to interpret the variables but for others this might be helpful? ;)

**Comment by Nickduino** [comment]
I'm willing to translate the variables (do we need to if there's a GUI, though?)

@MichaelB2018>  Does it still work on python 2.7 ?

**Comment by waltner** [comment]
> I'm willing to translate the variables (do we need to if there's a GUI, though?)

I think that would be nice independent of the GUI. There is some community (and forks) for your project, so it might attract additional PR. @alxlaxv and me made our own translated versions, I think others have too. One could also think about multi language support for the GUI...

**Comment by MichaelB2018** [comment]
@Nickduino => Yes, it does still work on python 2.7 ?
@waltner => I already translated the variables already to English.

will check it in s soon as I have the delay working

**Comment by alxlaxv** [comment]
Sounds great too!
I think this feature must be configurable and we need an ability to turn them on or off.
For example if you check my project, I removed all notion of sunrise sunset etc. Just simple function.
We could split and then have something configurable :)

**Comment by Nickduino** [comment]
About the weather, there something else I've been meaning to do: of it's really hot and sunny outside, only partially open the blinds in the morning instead.

**Comment by MichaelB2018** [comment]
OK, I checked in the change. Please be patient, as I would expect to find quite a few usability issues and bugs as this is a major upgrade and has not been widely tested. Just report it and I'll aim to fix it. You can find it here: https://github.com/MichaelB2018/Pi-Somfy. I also added quite a bit of documentation, hope that helps.

As for the comments
@lfliess : The problem I have with this is that rising the  retractable sunshade is the easy part and building an OWM integration is not difficult. BUT, you may also want to lower the sunshade. And I would assume that this is  much more complicated logic. You may want to do it at 10am, only between May and October, only if the wind is less than x m/s and only if the weather is expected to be sunny and above x degrees in the afternoon.  Building such a complex logic is not a trivial task and I would prefer to use existing tools for it. Maybe we should spend the time to integrate this software with Home Assistant or with MQTT. That way you can use the advanced functionality of Home Assistant to send commands to your sunshade. But happy to discuss potential ways to build this if you have better ideas

@alxlaxv : The code now allows to just schedule it at a fixed time, independent of sunset or sunrise

@Nickduino : suggest we test this change first before merging it back into your repo, which is probably still the best option.

**Comment by Nickduino** [comment]
Great job on the documentation!
And yeah, let's test it there before merging both repos.

As for the functionalities, I believe the GUI should include the location and sunset/sunrise like in your screenshot
Then the delay and stop command to partially open a blind

**Comment by Nickduino** [comment]
I've been battling with my Pi the half the afternoon, to no avail yet :-(
I'm wondering if I can install the latest pip on my old Pi.

Python 2.7:
`pi@RaspberryPi ~ $ sudo python /home/pi/somfy2/Pi-Somfy/operateShutters.py


This program requires the Flask library. Please see the project documentation at https://github.com/jgyates/genmon.

Error: No module named OpenSSL


This program requires the modules located from the same github repository that are not present.

Error: name 'sys' is not defined
`

Python3 (but pip3 doesn't really work):
`sudo python3 /home/pi/somfy2/Pi-Somfy/operateShutters.py
Traceback (most recent call last):
  File "/home/pi/somfy2/Pi-Somfy/operateShutters.py", line 10, in <module>
    import ephem
ImportError: No module named ephem
`

**Comment by MichaelB2018** [comment]
checked in a fix for OpenSSL so that the SSL stuff is not required unless you set UseHTTPS to true (ie you use https instead of http). Check that out

also if you update the first line of operateShutters.py to 

#!/usr/bin/python

instead of 

#!/usr/bin/python3

you can use Python 2.7. Maybe try that

**Comment by Nickduino** [comment]
> checked in a fix for OpenSSL so that the SSL stuff is not required unless you set UseHTTPS to true (ie you use https instead of http). Check that out

You mean https://github.com/MichaelB2018/Pi-Somfy/blob/master/operateShutters.conf#L33?
I didn't change it

**Comment by MichaelB2018** [comment]
@Nickduino. Drop me quick note at michaelb2018.github(at)gmail.com. Easier to work through these issues over email or google hangout.

Note that I will delete this message again in a few hours to prevent spam.

**Comment by Nickduino** [comment]
Looks promising :-)

![image](https://user-images.githubusercontent.com/9784237/51806222-b125ae00-2277-11e9-968b-cbfba8748db7.png)

**Comment by MichaelB2018** [comment]
indeed

**Comment by Nickduino** [comment]
Not quite yet

![image](https://user-images.githubusercontent.com/9784237/51806366-74f34d00-2279-11e9-8bd4-e1b7d1f366f1.png)

**Comment by MichaelB2018** [comment]
just what I wanted to say. The error message stated "Address already in use". Glad it works. Now up to the next step. Setting up your Shutters and Schedule.

**Comment by Nickduino** [comment]
> Now up to the next step. Setting up your Shutters 

Done


> and Schedule.

Not done.



Sswitching to email

**Comment by Nickduino** [comment]
Michael's additions have been merged into the main repository: https://github.com/Nickduino/Pi-Somfy/releases

I even published a release: https://github.com/Nickduino/Pi-Somfy/releases


We're looking for new talents to keep improving it, please make yourself known if you're motivated.
