### ISSUE TITLE
Sunset-sunrise as argument

### ISSUE THREAD

**Issue by Nickduino** [Nickduino/Pi-Somfy#20]
The way I see it, the day starts in the morning and end in the evening, I'd prefer it if the first argument passed was to open he blinds (accepting a negative value if you want to open them before sunrise) the the second to close them.

![image](https://user-images.githubusercontent.com/9784237/51987984-e57db200-24a3-11e9-8b04-23dccf61b2d1.png)

Moreover, we may want to use the astronomical data at night but not in the morning (open at 7 every day, close right after sunset) so I think we should seperate that in three arguments:
-    ``-t      time``
-    ``-m    sunrise``
-    ``-n    sunset``

**Comment by lfliess** [comment]
I'm working on adding support for Somfy Awnings.
for those, we need to do the opposite - you want to lower them (open) some time after sunrise, and rise them (close) some time before/after sunset.
So if anyone has time, making these changes would be great.

**Comment by Nickduino** [comment]
We should definitely do that.
The temporary solution is to lower/rise them at fixed hours for the moment.

**Comment by MichaelB2018** [comment]
Not sure I understand the ask here. Using the web interface it should be quite simple program what you suggest. The command line interface was never really meant for complex actions, but rather just as a debugging tool. But maybe I miss something. Have you tried doing the above using the web interface and add a "Scheduled Operation"?

**Comment by lfliess** [comment]
You're right, didn't realize webUI works as expected.
CLI should have the same ability, but it's not a must
