### ISSUE TITLE
Accents aren't recognised

### ISSUE THREAD

**Issue by Nickduino** [Nickduino/Pi-Somfy#23]
Trying to register shutter _Commande G**é**n**é**rale_

![image](https://user-images.githubusercontent.com/9784237/51995886-fc2c0500-24b3-11e9-888f-2b7887fac126.png)

**Comment by MichaelB2018** [comment]
it works well in Python 3. I didn't manage to get it to work easily in Python 2. So I stripped out the accents in Python 2, at least that way it works  without an error message.
