### ISSUE TITLE
Open-source license?

### ISSUE THREAD

**Issue by benesch** [Nickduino/Pi-Somfy#3]
Hi @Nickduino, thanks so much for making this code public! Just wanted to ask if you'd be willing to throw some sort of a open-source license on the code—I'm hoping to publish a modification that integrates with Amazon Alexa, and I don't want to be stealing your work. :beers:

**Comment by Nickduino** [comment]
Hi benesch,

I'm glad the code is useful to some people! I myself based it on a protocol decoding found on Pushtack.

Maybe you could fork the repo? Or just mention me in your code?
I don't want to bother people with licensing: use the code and be happy :)

**Comment by tholu** [comment]
@benesch Have you started on working on a version that integrates with Alexa? I'm planning the same thing.

**Comment by benesch** [comment]
Afraid I haven't made any progress yet.
