### ISSUE TITLE
Help choosing supported hardware.

### ISSUE THREAD

**Issue by SergikNk** [Nickduino/Pi-Somfy#30]
Hello, the technical specifications of my Somfy controller are the following:

_Radio frecuency: 868.95 MHZ, io-homecontrol
Frecuency band of trasmission: 868.700 MHz - 869.200MHz__

I been looking for a compatible crystal but I can't find anything on these frecuency. 
Would the model that you are using works for me?
Where could I find something compatible?

Thank you in advance :)

**Comment by Nickduino** [comment]
Sad news mate, there is **no** chance Pi-Somfy will work with your blinds. io-homecontrol® has nothing in common with the RTS protocol.

Somfy's solution is the TaHoma or Connexoon boxes. I've no idea if someone reverse-engineered the io-homecontrol® protocol (which is common to half a dozen brands)
