### ISSUE TITLE
Stop doesn't work when blind is going up

### ISSUE THREAD

**Issue by chrisevans1001** [Nickduino/Pi-Somfy#34]
Bit of an oddity. If I command the blind to go down, it does. If I try to stop it mid way, it stops fine. If I command the blind to go up, it does. If I try to stop it mid-way, nothing happens. If I use the remote to stop it after sending the up command via Pi-Somfy, it stops fine.

Within the log file for Pi-Somfy, the same button is showing as being pressed for stop whether the blind is going up or down and the rolling code sequence is correct.

Any suggestions?

Thanks

Chris

**Comment by Nickduino** [comment]
I've never experienced this behavior and it seems pretty weird indeed.

Have you tried sending the stop command several times? Putting the RF emitter closer to the blind? Changing the antenna?
(The only thing I can think off is that your blind's motor may emit more RF interferences when it's going up and it would have a harder time picking up a weak signal from the emitter)
