### ISSUE TITLE
Web Gui an Comandline together

### ISSUE THREAD

**Issue by dops84** [Nickduino/Pi-Somfy#37]
Hi,
how can I use Web Gui an Comandline together?
If Webgui is started, comands from comandline didn´t work.
Kind regards

**Comment by MichaelB2018** [comment]
Good point - never thought of it that way. Maybe best to enhance when we build the MQTT interface. Then we could have a small command line tool to send MQTT messages to the service.

**Comment by dops84** [comment]
I've found out that you can do it with curl commands.
here a sample:
/usr/bin/curl --data "shutter=0x253523" http://192.168.11.143/cmd/down

**Comment by MichaelB2018** [comment]
great idea! Thanks
