### ISSUE TITLE
Manual commands when WebUI is running

### ISSUE THREAD

**Issue by alxlaxv** [Nickduino/Pi-Somfy#43]
Hello,

Is there a way to be able to use manual commands like 
`sudo /home/pi/Pi-Somfy/operateShutters.py livingRoom -c /home/pi/Pi-Somfy/operateShutters.conf -d`
when the WebUi is running?
I would like to call it from other systems.
Or is there anyway to send cli instructions to the webinterface?

Best

**Comment by MichaelB2018** [comment]
Check question #37, s this was discussed there On Sep 21, 2019 06:00, alxlaxv <notifications@github.com> wrote:Hello,
Is there a way to be able to use manual commands like
sudo /home/pi/Pi-Somfy/operateShutters.py livingRoom -c /home/pi/Pi-Somfy/operateShutters.conf -d
when the WebUi is running?
I would like to call it from other systems.
Or is there anyway to send cli instructions to the webinterface?
Best

**Comment by alxlaxv** [comment]
Hello,
I have tried this but I got a status 200 ok but nothing happens
