### ISSUE TITLE
Conflict with official remote?

### ISSUE THREAD

**Issue by alxlaxv** [Nickduino/Pi-Somfy#44]
Hi,
I was using the new webinterface and planification for weeks and now it just stopped working.
I touched nothing but I recently used the official remote manual.
Is there any kind of conflict possible?

Should I remove and reprogram it now to have it back working?

Thanks

**Comment by Nickduino** [comment]
SSH into the Pi, then open the config file:
![image](https://user-images.githubusercontent.com/9784237/67752930-3242e900-fa34-11e9-8d9d-b37e790b2193.png)

Go check the rolling codes section:
![image](https://user-images.githubusercontent.com/9784237/67753032-5f8f9700-fa34-11e9-93bf-3a074bf4247e.png)

At the bottom of the list, do you have duplicate remote address?
(That would be in lower case)

**Comment by alxlaxv** [comment]
Hello,
In this section I have:
```
[ShutterRollingCodes]
0x279621 = 151
0x279622 = 7
```

**Comment by Nickduino** [comment]
That seems alright

> I was using the new webinterface and planification for weeks and now it just stopped working.

Do you mean you can't access the web interface anymore or that a button press stopped working?

**Comment by alxlaxv** [comment]
The recurrent task to open shaders in the morning just stopped to be executed.
So I have open the web interface and the buttons inside do nothing now.

**Comment by Nickduino** [comment]
After a button press on the GUI, the number in [ShutterRollingCodes] is incremented properly?


Have you checked your wiring? Any chance the emitter or antenna is faulty?

**Comment by alxlaxv** [comment]
Yes properly incremented. I will double check the wiring tomorrow as nothing changed there.

**Comment by alxlaxv** [comment]
Wiring is nothing, untouched.

**Comment by MichaelB2018** [comment]
If it properly increases the counter, it seems to me quite unlikely that the software broke. You say the wiring on the Pi is ok and the Shutter works fine with other remotes... then can you try to bring the Pi closer to the Shutter. I did see some fluctuations on how far it can reach.

**Comment by alxlaxv** [comment]
So, I have removed the whole cloned folder and cloned it again.
I tried to relaunch as-is and it says paho-mqtt is missing.
I have reinstalled all required packages and now it still doesn't react...
I'm a bit lost.

**Comment by Nickduino** [comment]
It's pretty hard to help you without more information.

I'm still inclined to think it could be a hardware problem. Wiring issue, cold solder joint, out-of-tune antenna, dead emitter, ...
