### ISSUE TITLE
How to test if the emitter works?

### ISSUE THREAD

**Issue by MatthiasGrandl** [Nickduino/Pi-Somfy#49]
I setup the software properly on my PI. Can't get my Awning (Markiluxx using Somfy) to pair though, even after putting it in programming mode. I have no clue whether or not the emitter works in the first place. Would appreciate any pointers.

**Comment by ttimpe** [comment]
Kind of the same situation here, I soldered the right crystal onto a FS 1000A however I am unable to get any response from my shutters.

**Comment by Nickduino** [comment]
I'd say either use the algorithm (or my Arduino version) to create a Somfy decoder or check your wiring 10 times

**Comment by Ezezi3l** [comment]
it is very easy to test the emitter with a SDR dongle and SDR Sharp software.

**Comment by MichaelB2018** [comment]
could you post some detailed instructions on how to test an emitter, many people (like me) may find this useful.

**Comment by Ezezi3l** [comment]
- you need a simple SDR usb receiver like this one: https://www.adafruit.com/product/1497
- install and setup SDRSharp from: https://airspy.com/download/
- follow instruction to install the correct usb driver
In SDRSharp listen to the frequency 443.42Mhz.
Send an instruction to one shutter and you should see a short communication on 443.42Mhz
![SDR](https://user-images.githubusercontent.com/62930017/79766836-cbd6bd80-8328-11ea-8c10-d50cf699a52f.png)

**Comment by StarScream159** [comment]
This would work for testing right? https://www.amazon.ca/digital-Stick-RTL-SDR-Receiver-RTL2832U/dp/B00CM3LNMM/

**Comment by Nickduino** [comment]
@Ezezi3l Can you also read the data sent by the remote (in binary or hex) or is it just a spectrum analyser?

**Comment by rbswift** [comment]
This might be a good place to start... https://pushstack.wordpress.com/2014/05/17/somfy-rtl-sdr/

**Comment by Nickduino** [comment]
Good! That's the guy who originally reverse engineered the protocol

**Comment by kjellhult** [comment]
In terms of the hardware -- when you replace the crystal, keep in mind that one of the three pins is grounded to the metal case and the others have *very small* insulators around their pads.  Make sure you clean up any excess solder and consider a small air gap between the emitter and the board to make sure the other two pins don't short to ground.  I was having intermittent issues until I re-soldered the oscillator with a tiny gap between the board and the case.

**Comment by StarScream159** [comment]
@kjellhult can you post a really close up picture of how you soldered the oscillator?

**Comment by kjellhult** [comment]
![20200924_062639](https://user-images.githubusercontent.com/70078858/94166008-ae5dd080-fe3f-11ea-8fcf-03a9ec93becf.jpg)
I've attached a close-up photo of the oscillator kind of floating off the surface of the board to prevent any bleed-through solder from the pins other than the ground pin from shorting the metal case to another pin.  With any luck this helps - it certainly was an issue for me with my crappy soldering skills.
