### ISSUE TITLE
Where can I buy the emitter ?

### ISSUE THREAD

**Issue by grout-r** [Nickduino/Pi-Somfy#6]
Hi,

Do you have any recommendation about which emitter buy ?

I looked on Aliexpress but I don't know what to buy.

Thanks

**Comment by grout-r** [comment]
Oops didnt look in closed issues, you can delete this one

**Comment by Nickduino** [comment]
> Oops didnt look in closed issues, you can delete this one

Kudos for searching by yourself! Let me know if tou run into issues. If you are into Arduino as well, you can check my other repo ;-)

**Comment by grout-r** [comment]
Ok thanks !
As i like python better than C, i'll stick with raspi for the moment :)

**Comment by Nickduino** [comment]
I wouldn't have been able to do it in C on the Raspberry Pi (thank god I found that C library you can use with Python) but Arduino is easy.

**Comment by z4nD4R** [comment]
@Nickduino I'm just finghting with somfy and ESP32 do you have any useful tutorial?
