### ISSUE TITLE
Can I make this on a ESP-8266?

### ISSUE THREAD

**Issue by joaolucasd** [Nickduino/Pi-Somfy#69]
Hi guys, total noob here.

I have a Raspberry pi3 that runs a couple on automations. I tried installing Pi-Somfy in it, but without success. I just can't "sudo it".

I have an ESP-8266 that would work even better, since it has wifi and I can move closer to the courtain. Is it possible to do it?

**Comment by Nickduino** [comment]
I don't think the ESP8266 is better suited but it's possible. Look at the forks, some people ported it to that plateform with LUA and whatnot
