### ISSUE TITLE
Somfy RF reader

### ISSUE THREAD

**Issue by geokscott** [Nickduino/Pi-Somfy#83]
How hard would it be to set up a receiver that could decode remote commands?  It would be nice to make it two-way so a true integration with Home Assistant could be developed.

**Comment by lepirlouit** [comment]
I would be interested by this too.
I already have the hardware receiver https://www.amazon.fr/433Mhz-Wireless-Transmitter-Receiver-Arduino/dp/B00IOB9CWE
How to specificly listen on 433.42mhz
Also we need to separate the concept of "blind/shutter" and "remote controller"

**Comment by Nickduino** [comment]
TD;LR: I don't have a use for it (nope, not even "just for fun") so I won't do it. But you can.


Receiver frequency probably won't be an issue: the Chinese receivers aren't that picky. So you have to capture the frame and reverse the obfuscation procedure to know what command was sent to what shutter. Everything you need is in the code or the Pushstack article, that's probably still a few days of work but it's very doable.

**Comment by lepirlouit** [comment]
what do you mean with the Pushstack article ?

**Comment by Nickduino** [comment]
This:

![image](https://user-images.githubusercontent.com/9784237/89274962-f16ea500-d641-11ea-85a1-1079d67cb44f.png)
