### ISSUE TITLE
Dead link to eBay "fancy" antenna

### ISSUE THREAD

**Issue by numericOverflow** [Nickduino/Pi-Somfy#86]
Your eBay link to the "fancy" antenna is dead

`Literally any 17 cm solid core copper wire will do the job. But if you prefer to order a fancy full one, this one will come handy
Order`

Maybe just a picture or description of what you used would be good to avoid dead links in the future?

**Comment by Nickduino** [comment]
Hum...it's working for me

![image](https://user-images.githubusercontent.com/9784237/89686140-12631e80-d8fe-11ea-91eb-2ec54d9d349e.png)


But again you really don't need a finely tuned antenna, the shutters don't care

**Comment by numericOverflow** [comment]
Yeah, weird - now it's working for me too.  When I tried it a day or two ago, eBay was throwing some generic "auction can't be found" error.  I just figured too much time elapsed and they purged the listing since the other links had worked OK. 

Oh well, must have been user/device error. Thanks for checking
