### ISSUE TITLE
shutters not responding anymore

### ISSUE THREAD

**Issue by W11T** [Nickduino/Pi-Somfy#92]
We have nine shutters and some schedules to raise them up in the morning and shut them down in the evening.
This worked for a while. Yesterday only some shut down. None raised in the morning and now none is responding any more.
Is this an issue of rolling codes?
We used the somfy RTS to operate the shutters in the meantime.
How to get this fixed?

**Comment by Nickduino** [comment]
Can you launch the GUI or does it crash?
Have you had a look at your logs?

**Comment by W11T** [comment]
I'm sorry for getting back late.
Actually Pi-Somfy is working well since a while. I guess this was rather an issue of my Raspis GPIOs.
